try:
    print(10/0)
except:
    print("Se ha producido un error")
finally:
    print("Ha dinalizado el manejo de excepciones")